service: smec-example

package:
  include:
    - "handlers/*.py"
    - "managers/*.py"
    - "models/*.py"
  exclude:
    - "**/**"

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  stackTags:
    PRODUCT: example
    STAGE: ${self:provider.stage}
  apiGateway:
    restApiId: ${ssm:/${self:service}/api_id/${self:provider.stage}}
    restApiRootResourceId: ${ssm:/${self:service}/api_base/${self:provider.stage}}
    
functions:
#  test:
#    name: ${self:service}-test-${self:provider.stage}
#    handler: handlers/test.lambda_handler
#    events:
#      - http:
#          path: test
#          method: get
#          cors: true

  list:
    handler: handlers/TPIHandler.list      
    events:
      - http:
          path: tpi
          method: get 
          cors: true

  create:
    handler: handlers/TPIHandler.create
    events:
      - http:
          path: tpi
          method: post
          cors: true

  read:
    handler: handlers/TPIHandler.read
    events:
      - http:
          path: tpi/{id}
          method: get
          cors: true
          integration: lambda
          request:
            paths:
              id: true

  update:
    handler: handlers/TPIHandler.update
    events:
      - http:
          path: tpi/{id}
          method: put
          cors: true
          integration: lambda
          request:
            paths:
              id: true
  
  delete:
    handler: handlers/TPIHandler.delete
    events:
      - http:
          path: tpi/{id}
          method: delete
          cors: true
          integration: lambda
          request:
            paths:
              id: true
